package com.ledgerflow.core.crypto.kem

import com.google.common.truth.Truth.assertThat
import com.ledgerflow.core.crypto.kdf.Hkdf
import java.math.BigInteger
import java.security.SecureRandom
import org.junit.Test

/**
 * Golden vectors for the backup sealing key (ADR-0027). **If this fails, the
 * code is wrong — never re-record it** (`SPEC.md` §7.2's rule for the phrase
 * derivation, which this sits beside).
 *
 * Two independent sources, because a vector produced by the thing it checks
 * proves nothing:
 *
 * 1. **RFC 9180's own published vectors** for DHKEM(P-256, HKDF-SHA256), base
 *    mode, taken from the CFRG working group's `test-vectors.json` (mode 0,
 *    kem_id 16, kdf_id 1, aead_id 1). These pin `DeriveKeyPair`, encapsulation
 *    and decapsulation against the standard itself.
 * 2. **LedgerFlow's own layer** — a BIP-39 seed through to `backupKey` and
 *    `keyCheck` — generated by a separate Python implementation written from
 *    the RFC, which was first checked against source 1 on every value.
 *
 * The phrase used throughout is the **public BIP-39 test vector** (`abandon`
 * ×23 then `art`). It is nobody's key, and no real phrase ever appears here.
 */
class BackupSealKemVectorTest {

    // ── 1. RFC 9180, Appendix A.3 (base mode) ───────────────────────────────

    private val rfcIkmE = "4270e54ffd08d79d5928020af4686d8f6b7d35dbe470265f1f5aa22816ce860e".hex()
    private val rfcSkEm = BigInteger("4995788ef4b9d6132b249ce59a77281493eb39af373d236a1fe415cb0c2d7beb", 16)
    private val rfcSkRm = BigInteger("f3ce7fdae57e1a310d87f1ebbde6f328be0a99cdbcadf4d6589cf29de4b8ffd2", 16)
    private val rfcPkRm = (
        "04fe8c19ce0905191ebc298a9245792531f26f0cece2460639e8bc39cb7f706a82" +
            "6a779b4cf969b8a0e539c7f62fb3d30ad6aa8f80e30f1d128aafd68a2ce72ea0"
        ).hex()
    private val rfcEnc = (
        "04a92719c6195d5085104f469a8b9814d5838ff72b60501e2c4466e5e67b325ac9" +
            "8536d7b61a1af4b78e5b7f951c0900be863c403ce65c9bfcb9382657222d18c4"
        ).hex()
    private val rfcSharedSecret = "c0d26aeab536609a572b07695d933b589dcf363ff9d93c93adea537aeabb8cb8".hex()

    @Test
    fun deriveKeyPair_matchesTheRfc() {
        assertThat(BackupSealKem.deriveScalar(rfcIkmE)).isEqualTo(rfcSkEm)
    }

    @Test
    fun encapsulation_matchesTheRfc() {
        val sealed = BackupSealKem.encapsulate(rfcPkRm, rfcSkEm)

        assertThat(sealed.enc).isEqualTo(rfcEnc)
        assertThat(sealed.sharedSecret).isEqualTo(rfcSharedSecret)
    }

    @Test
    fun decapsulation_matchesTheRfc() {
        assertThat(BackupSealKem.decapsulate(rfcSkRm, rfcEnc)).isEqualTo(rfcSharedSecret)
    }

    // ── 2. LedgerFlow's own layer ───────────────────────────────────────────

    private val seed = (
        "408b285c123836004f4b8842c89324c1f01382450c0d439af345ba7fc49acf70" +
            "5489c6fc77dbd4e3dc1dd8cc6bc9f043db8ada1e243c4a0eafb290d399480840"
        ).hex()
    private val publicKey = (
        "04b1422357008f10355dae5517bdeda89b4fe4ddb829894770b7300a8e08b1a6fb" +
            "0615444c8cf2353a6300995b209bc0a25b35de4c0dceb103a33fcda5212971d9"
        ).hex()
    private val ephemeralScalar = BigInteger("1725776bb1891cb23f712c53a8ad39117f35bd28a9e8920463383021c7a0445d", 16)
    private val enc = (
        "0448572076e309a32978d5189f60d37b1f7f97d7b025b6609263669f4de6f20d08" +
            "2b44cf51c0f11716075b2469443e00f0d4825bf54f785b0173e346c41fb2b088"
        ).hex()
    private val sharedSecret = "eb965cacfc07ebf29618ce53fa66ce76cad06a982468fb82ddc7556e334797f0".hex()
    private val salt = "000102030405060708090a0b0c0d0e0f".hex()

    @Test
    fun publicKey_fromTheTestPhrasesSeed_isPinned() {
        assertThat(BackupSealKem.publicKey(seed)).isEqualTo(publicKey)
    }

    @Test
    fun sealing_withAPinnedEphemeralKey_isPinned() {
        val sealed = BackupSealKem.encapsulate(publicKey, ephemeralScalar)

        assertThat(sealed.enc).isEqualTo(enc)
        assertThat(sealed.sharedSecret).isEqualTo(sharedSecret)
    }

    @Test
    fun openingWithTheSeed_reproducesTheSharedSecret() {
        assertThat(BackupSealKem.open(seed, enc)).isEqualTo(sharedSecret)
    }

    /** The two values the container will carry, pinned where the file format can see them. */
    @Test
    fun backupKeyAndKeyCheck_arePinned() {
        val backupKey = Hkdf.derive(sharedSecret, salt, "lfbk-backup-v2".toByteArray(), BACKUP_KEY_BYTES)
        val keyCheck = Hkdf.derive(publicKey, salt, "lfbk-keycheck-v2".toByteArray(), KEY_CHECK_BYTES)

        assertThat(backupKey).isEqualTo("5efb1013d99ef3c17147ca8c0e291df27f85217dc76998daed671828047b22a8".hex())
        assertThat(keyCheck).isEqualTo("2ae5e758".hex())
    }

    // ── Properties the vectors cannot state ─────────────────────────────────

    /** Sealing twice must never repeat: a reused ephemeral key repeats the file's key. */
    @Test
    fun everySealIsFresh() {
        val first = BackupSealKem.seal(publicKey, SecureRandom())
        val second = BackupSealKem.seal(publicKey, SecureRandom())

        assertThat(first.enc).isNotEqualTo(second.enc)
        assertThat(first.sharedSecret).isNotEqualTo(second.sharedSecret)
        assertThat(BackupSealKem.open(seed, first.enc)).isEqualTo(first.sharedSecret)
        assertThat(BackupSealKem.open(seed, second.enc)).isEqualTo(second.sharedSecret)
    }

    /** A different phrase opens nothing — the property the whole design rests on. */
    @Test
    fun anotherSeedOpensNothing() {
        val sealed = BackupSealKem.seal(publicKey)
        val otherSeed = ByteArray(64) { 7 }

        assertThat(BackupSealKem.open(otherSeed, sealed.enc)).isNotEqualTo(sealed.sharedSecret)
    }

    private fun String.hex(): ByteArray = chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private companion object {
        const val BACKUP_KEY_BYTES = 32
        const val KEY_CHECK_BYTES = 4
    }
}
