package com.ledgerflow.core.data.ingest

import com.google.common.truth.Truth.assertThat
import com.ledgerflow.core.domain.ingest.ExtractedDirection
import com.ledgerflow.core.domain.ingest.ExtractedLineItem
import com.ledgerflow.core.domain.ingest.ExtractedTransaction
import com.ledgerflow.core.model.LineItemKind
import com.ledgerflow.core.model.Money
import org.junit.Test

/**
 * The payload's version ladder (ADR-0022).
 *
 * ## Why this exists
 *
 * ADR-0022 declines to build `pending_line_item` and puts an itemised
 * candidate's lines in `extracted_json` instead. That trade is only sound if
 * the payload can be extended without orphaning what is already in a user's
 * vault — a schema migration is loud and tested, a JSON format change is
 * neither. So the compatibility this file asserts is what the ADR spent to buy
 * its simplicity, and it has to be checked rather than assumed.
 *
 * ## The v1 fixture is never re-recorded
 *
 * [V1_PAYLOAD] is a literal, byte-for-byte, of what a v1 build wrote. It is not
 * generated by this code and must never be regenerated to match new output —
 * the same rule `CLAUDE.md` §7 states for the crypto golden vectors, for the
 * same reason: if it fails, the reader changed in a way that would silently
 * misread rows that already exist on a device. Regenerating it would make the
 * test agree with the bug.
 */
class ExtractedTransactionJsonVersionTest {

    private companion object {
        /**
         * A real v1 encoding, captured before v2 existed.
         *
         * Note what is *absent*: no `lines` key at all, and `explicitNulls =
         * false` means the unset optional fields are absent rather than null.
         * Both are properties of the v1 writer, so a fixture that included them
         * would be testing a payload no build ever produced.
         */
        const val V1_PAYLOAD =
            """{"v":1,"amountMinor":78800,"currency":"INR","direction":"DEBIT",""" +
                """"merchantRaw":"RAMESH KUMAR","accountLast4":"9902",""" +
                """"instrumentHint":"UPI","occurredAt":1787000000000,"confidence":0.9}"""
    }

    // ── Backward: a v1 row on disk still reads ──────────────────────────────

    @Test
    fun aV1Payload_stillDecodes() {
        val decoded = ExtractedTransactionJson.decode(V1_PAYLOAD)

        assertThat(decoded).isNotNull()
        requireNotNull(decoded)
        assertThat(decoded.amount).isEqualTo(Money(78_800))
        assertThat(decoded.currency).isEqualTo("INR")
        assertThat(decoded.direction).isEqualTo(ExtractedDirection.DEBIT)
        assertThat(decoded.merchantRaw).isEqualTo("RAMESH KUMAR")
        assertThat(decoded.accountLast4).isEqualTo("9902")
        assertThat(decoded.occurredAt).isEqualTo(1_787_000_000_000L)
        assertThat(decoded.confidence).isEqualTo(0.9)
    }

    /**
     * And its lines are empty, which is **true rather than lossy**.
     *
     * Every v1 payload came from an SMS or a notification, and a bank message
     * carries one amount — there is nothing to itemise and never was. This is
     * the assertion that says the v2 bump needs no migration and no re-encode
     * pass over existing rows.
     */
    @Test
    fun aV1Payload_hasNoLinesAndThatIsCorrect() {
        val decoded = ExtractedTransactionJson.decode(V1_PAYLOAD)

        assertThat(decoded?.lines).isEmpty()
    }

    // ── Forward: v2 round-trips, including the awkward parts ────────────────

    @Test
    fun aV2Payload_roundTripsItsLines() {
        val original = ExtractedTransaction(
            amount = Money(47_300),
            currency = "INR",
            direction = ExtractedDirection.DEBIT,
            merchantRaw = "LOCAL KIRANA",
            confidence = 0.82,
            lines = listOf(
                ExtractedLineItem(
                    name = "RICE 5KG",
                    kind = LineItemKind.ITEM,
                    quantityMilli = 1_000,
                    unitPrice = Money(42_000),
                    total = Money(42_000),
                    confidence = 0.91,
                ),
                // Half a kilo: the case a Double would round-trip wrong, and the
                // reason quantity is milli-units rather than a fraction.
                ExtractedLineItem(
                    name = "TOMATO",
                    kind = LineItemKind.ITEM,
                    quantityMilli = 500,
                    unitPrice = Money(4_000),
                    total = Money(2_000),
                    confidence = 0.77,
                ),
                ExtractedLineItem(name = "CGST 2.5%", kind = LineItemKind.TAX, total = Money(300)),
                ExtractedLineItem(name = "ROUNDING", kind = LineItemKind.DISCOUNT, total = Money(-100)),
            ),
        )

        val decoded = ExtractedTransactionJson.decode(ExtractedTransactionJson.encode(original))

        assertThat(decoded).isEqualTo(original)
    }

    /**
     * A line the extractor could only half-read survives as a half-read line.
     *
     * §5.1's never-silently-drop rule, one grain down: a price with no name and
     * a name with no price are both things OCR produces on a real receipt, and
     * the review screen can only show what the payload can carry.
     */
    @Test
    fun aPartiallyReadLine_survivesTheRoundTrip() {
        val original = ExtractedTransaction(
            direction = ExtractedDirection.DEBIT,
            lines = listOf(
                ExtractedLineItem(name = "UNREADABLE PRICE", total = null, unitPrice = null),
                ExtractedLineItem(name = "?", total = Money(15_000), quantityMilli = null),
            ),
        )

        val decoded = ExtractedTransactionJson.decode(ExtractedTransactionJson.encode(original))

        assertThat(decoded?.lines).hasSize(2)
        assertThat(decoded?.lines?.get(0)?.total).isNull()
        assertThat(decoded?.lines?.get(1)?.total).isEqualTo(Money(15_000))
    }

    /**
     * A negative line total survives.
     *
     * `line_item.total_minor` is signed so that a DISCOUNT row is negative and
     * every consumer that sums lines is correct without knowing what a `kind`
     * means (§6.1). A payload that dropped the sign would put that arithmetic
     * back on the reader.
     */
    @Test
    fun aNegativeLineTotal_keepsItsSign() {
        val original = ExtractedTransaction(
            lines = listOf(ExtractedLineItem(name = "OFFER", kind = LineItemKind.DISCOUNT, total = Money(-5_000))),
        )

        val decoded = ExtractedTransactionJson.decode(ExtractedTransactionJson.encode(original))

        assertThat(decoded?.lines?.single()?.total).isEqualTo(Money(-5_000))
    }

    /**
     * A kind this build does not know degrades to ITEM rather than dropping.
     *
     * The same position the enum fallbacks already take on `direction` and
     * `instrumentHint`: a line under the wrong kind is visible and correctable,
     * a line that vanished is neither. Simulates a payload from a build that
     * added a kind this one has never heard of.
     */
    @Test
    fun anUnknownLineKind_degradesToItemRatherThanDroppingTheLine() {
        val fromTheFuture =
            """{"v":3,"direction":"DEBIT","confidence":0.5,""" +
                """"lines":[{"name":"DEPOSIT REFUND","kind":"BOTTLE_DEPOSIT","totalMinor":2000}]}"""

        val decoded = ExtractedTransactionJson.decode(fromTheFuture)

        assertThat(decoded?.lines).hasSize(1)
        assertThat(decoded?.lines?.single()?.name).isEqualTo("DEPOSIT REFUND")
        assertThat(decoded?.lines?.single()?.kind).isEqualTo(LineItemKind.ITEM)
        assertThat(decoded?.lines?.single()?.total).isEqualTo(Money(2_000))
    }

    /** Malformed is null, not a crash — one bad row must not close the Inbox. */
    @Test
    fun aMalformedPayload_decodesToNull() {
        assertThat(ExtractedTransactionJson.decode("not json at all")).isNull()
    }

    @Test
    fun theVersionIsWrittenOnEveryPayload() {
        val encoded = ExtractedTransactionJson.encode(ExtractedTransaction())

        assertThat(encoded).contains("\"v\":${ExtractedTransactionJson.VERSION}")
    }
}
